/**
 * Global polyfills for React Native (Hermes).
 *
 * Hermes has no Web Crypto API; the `uuid` package (v4) calls
 * `crypto.getRandomValues()`.
 *
 * Preferred provider is expo-crypto's native implementation, BUT that is a
 * native module: it only exists inside a dev-client / production build made
 * AFTER expo-crypto was added to package.json. Older dev-clients crash with
 * "Cannot find native module 'ExpoCrypto'" at import time.
 *
 * Therefore: lazy-load expo-crypto on FIRST CALL instead of import time,
 * and fall back to a non-native entropy pool when the native module is
 * missing (e.g. old dev-client builds). The fallback mixes several weak
 * entropy sources through a xorshift generator — adequate for UUIDv4
 * identifiers, NOT for cryptographic keys (device keys are generated by
 * storage.native.ts separately).
 */

type RngFn = <T extends ArrayBufferView>(array: T) => T;
type CryptoGlobal = typeof globalThis & {
  crypto?: { getRandomValues?: RngFn };
};

const g = globalThis as CryptoGlobal;

// --- Fallback RNG (pure JS, no native modules) ---
let xorshiftState = 0;
const seedPool = () => {
  let s = (Date.now() ^ Math.floor(Math.random() * 0xffffffff)) >>> 0 || 0x9e3779b9;
  // Stir with timing jitter for a little extra variance.
  for (let i = 0; i < 8; i++) {
    s ^= s << 13; s >>>= 0;
    s ^= s >> 17;
    s ^= s << 5; s >>>= 0;
  }
  xorshiftState = s || 0x9e3779b9;
};
seedPool();

const fallbackGetRandomValues: RngFn = (array) => {
  const bytes = new Uint8Array(
    array.buffer as ArrayBuffer,
    array.byteOffset,
    array.byteLength,
  );
  for (let i = 0; i < bytes.length; i++) {
    if (i % 4 === 0) {
      // refill 4 bytes per step
      xorshiftState ^= xorshiftState << 13; xorshiftState >>>= 0;
      xorshiftState ^= xorshiftState >>> 17;
      xorshiftState ^= xorshiftState << 5; xorshiftState >>>= 0;
    }
    bytes[i] = (xorshiftState >>> ((i % 4) * 8)) & 0xff;
  }
  return array;
};

// --- Native provider (lazy, optional) ---
let nativeImpl: RngFn | null | undefined;

const resolveNative = (): RngFn | null => {
  if (nativeImpl !== undefined) return nativeImpl;
  try {
    // Check for the NATIVE module first, WITHOUT evaluating expo-crypto's JS
    // (its ExpoCrypto.js calls requireNativeModule at import time, which
    // throws on dev-clients built before expo-crypto existed).
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { requireOptionalNativeModule } = require('expo-modules-core');
    const nativeMod = requireOptionalNativeModule?.('ExpoCrypto');
    if (!nativeMod) {
      nativeImpl = null;
      return nativeImpl;
    }
    // Native module present — safe to evaluate the JS wrapper now.
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const Crypto = require('expo-crypto');
    const impl: unknown = Crypto?.getRandomValues;
    nativeImpl = typeof impl === 'function' ? (impl as RngFn) : null;
  } catch {
    // Native ExpoCrypto module absent (dev-client built before expo-crypto)
    nativeImpl = null;
  }
  return nativeImpl;
};

if (!g.crypto || typeof g.crypto.getRandomValues !== 'function') {
  g.crypto = Object.assign({}, g.crypto ?? {}, {
    getRandomValues: (array: ArrayBufferView) =>
      resolveNative()?.(array) ?? fallbackGetRandomValues(array),
  });
}
